force-app/main/default/objects/Exception__c/Exception__c.object-meta.xml
<CustomObject>
    <label>Exception</label>
    <nameField>
        <displayFormat>EX - {0000}</displayFormat>
        <label>Exception Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <label>Exception Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Exception_Caused_by__c.field-meta.xml
<CustomField>
    <fullName>Exception_Caused_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Caused by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Exceptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exception__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ApexException.cls
public class ApexException extends Exception {
    public static void logExceptions(Exception excptn)
    {
            Exception__c objException = new Exception__c();
            objException.Exception_Message__c=excptn.getMessage();
            objException.Stack_Trace__c=excptn.getStackTraceString();
            objException.Exception_Cause__c=string.valueOf(excptn.getCause());
            objException.Exception_Type__c=excptn.getTypeName();
            objException.Exception_Caused_by__c=userInfo.getUserId();
            upsert objException;
        
    }
    
    
}